[project]
authors = ["Chris Fonnesbeck <fonnesbeck@gmail.com>", "Alexandre Andorra <andorra.alexandre@gmail.com>"]
channels = ["conda-forge"]
description = "A Beginner's Guide to Variational Inference"
name = "pymc_vi_course"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
hvplot = "*"
ipython = "*"
ipywidgets = ">=8.1.5,<9"
jupyter_client = "*"
jupyter_core = "*"
jupyterlab = ">=4.3.6,<5"
pandas = "*"
patsy = "*"
pip = ">=25.0.1,<26"
polars = "*"
pyarrow = "*"
pymc = "*"
pydot = "*"
python-graphviz = "*"
scipy = "*"
seaborn = "*"
setuptools = "*"
watermark = "*"
preliz = ">=0.12.0,<0.13"
altair = ">=5.5.0,<6"
nutpie = ">=0.13.2,<0.14"
numba = ">=0.60.0,<0.61"
xlrd = ">=2.0.1,<3"
jupyter_bokeh = ">=4.0.5,<5"
plotly = ">=6.0.1,<7"
jupytext = ">=1.16.7,<2"
blackjax = ">=1.2.4,<2"
mystmd = ">=1.3.25,<2"
jupyterlab-myst = ">=2.4.2,<3"

[pypi-dependencies]
# jax = "*" # removed this bc it was causing issues with jax.numpy
numpyro = { version = "*", extras = ["cpu"] }
pymc-extras = ">=0.2.3, <0.3"
kaleido = ">=0.2.1, <0.3"
